# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Assemble the release build"
  lane :hard_deploy do
    gradle(task: "clean assembleRelease")
    upload_to_app_center
  end

  desc 'Upload to app center'
  lane :upload_to_app_center do
    appcenter_upload(
      api_token: "b1e80be5f29b4e9bf8ede6e114affe3679ed7f01",
      owner_name: "thomasn-bam.tech", # User name as it appears in the URL
      owner_type: "user",
      app_name: "qweAndroid", # The name of the app as it appears in the URL
      file: "app/build/outputs/apk/release/app-release.apk", # Path to the APK file to upload
    )
  end
end
